FROM golang:1.19.13-alpine AS build

RUN apk --no-cache add make

WORKDIR /pinspire_messenger

COPY go.mod go.sum /pinspire_messenger/
RUN go mod download

COPY . .

RUN make build_messenger

FROM alpine:latest

WORKDIR /

COPY --from=build /pinspire_messenger/bin/messenger .

ENTRYPOINT [ "./messenger" ]
