FROM golang:1.19.13-alpine AS build

RUN apk --no-cache add make

WORKDIR /pinspire

COPY go.mod go.sum /pinspire/
RUN go mod download

COPY . .

RUN make build_realtime

FROM alpine:latest

WORKDIR /

COPY --from=build /pinspire/bin/realtime .

ENTRYPOINT [ "./realtime" ]
