// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package share

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson16eb09bcDecodeGithubComGoParkMailRu20232ONDTeamInternalPkgEntityShare(in *jlexer.Lexer, out *SharedLink) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "role":
			out.Role = string(in.String())
		case "users_distributed":
			if in.IsNull() {
				in.Skip()
				out.Users = nil
			} else {
				in.Delim('[')
				if out.Users == nil {
					if !in.IsDelim(']') {
						out.Users = make([]int, 0, 8)
					} else {
						out.Users = []int{}
					}
				} else {
					out.Users = (out.Users)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					v1 = int(in.Int())
					out.Users = append(out.Users, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "is_distributed_all":
			out.IsDistributedAll = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16eb09bcEncodeGithubComGoParkMailRu20232ONDTeamInternalPkgEntityShare(out *jwriter.Writer, in SharedLink) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"users_distributed\":"
		out.RawString(prefix)
		if in.Users == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Users {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"is_distributed_all\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDistributedAll))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SharedLink) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16eb09bcEncodeGithubComGoParkMailRu20232ONDTeamInternalPkgEntityShare(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SharedLink) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16eb09bcEncodeGithubComGoParkMailRu20232ONDTeamInternalPkgEntityShare(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SharedLink) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16eb09bcDecodeGithubComGoParkMailRu20232ONDTeamInternalPkgEntityShare(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SharedLink) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16eb09bcDecodeGithubComGoParkMailRu20232ONDTeamInternalPkgEntityShare(l, v)
}
