// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: roll.proto

package roll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RollID     int32  `protobuf:"varint,1,opt,name=RollID,proto3" json:"RollID,omitempty"`
	QuestionID int32  `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
	Answer     string `protobuf:"bytes,3,opt,name=Answer,proto3" json:"Answer,omitempty"`
}

func (x *RollAnswer) Reset() {
	*x = RollAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollAnswer) ProtoMessage() {}

func (x *RollAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollAnswer.ProtoReflect.Descriptor instead.
func (*RollAnswer) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{0}
}

func (x *RollAnswer) GetRollID() int32 {
	if x != nil {
		return x.RollID
	}
	return 0
}

func (x *RollAnswer) GetQuestionID() int32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

func (x *RollAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type RollAnswers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*RollAnswer `protobuf:"bytes,1,rep,name=Answers,proto3" json:"Answers,omitempty"`
}

func (x *RollAnswers) Reset() {
	*x = RollAnswers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollAnswers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollAnswers) ProtoMessage() {}

func (x *RollAnswers) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollAnswers.ProtoReflect.Descriptor instead.
func (*RollAnswers) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{1}
}

func (x *RollAnswers) GetAnswers() []*RollAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type RollStatHist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer    string `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`
	Frequency int32  `protobuf:"varint,2,opt,name=Frequency,proto3" json:"Frequency,omitempty"`
}

func (x *RollStatHist) Reset() {
	*x = RollStatHist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollStatHist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollStatHist) ProtoMessage() {}

func (x *RollStatHist) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollStatHist.ProtoReflect.Descriptor instead.
func (*RollStatHist) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{2}
}

func (x *RollStatHist) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *RollStatHist) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type RollUserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RollID int32 `protobuf:"varint,1,opt,name=RollID,proto3" json:"RollID,omitempty"`
	UserID int32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *RollUserData) Reset() {
	*x = RollUserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollUserData) ProtoMessage() {}

func (x *RollUserData) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollUserData.ProtoReflect.Descriptor instead.
func (*RollUserData) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{3}
}

func (x *RollUserData) GetRollID() int32 {
	if x != nil {
		return x.RollID
	}
	return 0
}

func (x *RollUserData) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type HasAnswered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasAnswered bool `protobuf:"varint,1,opt,name=HasAnswered,proto3" json:"HasAnswered,omitempty"`
}

func (x *HasAnswered) Reset() {
	*x = HasAnswered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasAnswered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasAnswered) ProtoMessage() {}

func (x *HasAnswered) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasAnswered.ProtoReflect.Descriptor instead.
func (*HasAnswered) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{4}
}

func (x *HasAnswered) GetHasAnswered() bool {
	if x != nil {
		return x.HasAnswered
	}
	return false
}

type Nothing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy bool `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{5}
}

func (x *Nothing) GetDummy() bool {
	if x != nil {
		return x.Dummy
	}
	return false
}

type HisStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RollId     int32 `protobuf:"varint,1,opt,name=RollId,proto3" json:"RollId,omitempty"`
	QuestionID int32 `protobuf:"varint,2,opt,name=QuestionID,proto3" json:"QuestionID,omitempty"`
}

func (x *HisStatRequest) Reset() {
	*x = HisStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roll_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HisStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HisStatRequest) ProtoMessage() {}

func (x *HisStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roll_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HisStatRequest.ProtoReflect.Descriptor instead.
func (*HisStatRequest) Descriptor() ([]byte, []int) {
	return file_roll_proto_rawDescGZIP(), []int{6}
}

func (x *HisStatRequest) GetRollId() int32 {
	if x != nil {
		return x.RollId
	}
	return 0
}

func (x *HisStatRequest) GetQuestionID() int32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

var File_roll_proto protoreflect.FileDescriptor

var file_roll_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x6f,
	0x6c, 0x6c, 0x22, 0x5c, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x6c, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x52, 0x6f, 0x6c, 0x6c, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x22, 0x39, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x6c, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12,
	0x2a, 0x0a, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x07, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x22, 0x44, 0x0a, 0x0c, 0x52,
	0x6f, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x48, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x22, 0x3e, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x6c, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x2f, 0x0a, 0x0b, 0x48, 0x61, 0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x48, 0x61, 0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x48, 0x61, 0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x65, 0x64, 0x22, 0x1f, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x75,
	0x6d, 0x6d, 0x79, 0x22, 0x48, 0x0a, 0x0e, 0x48, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x32, 0xb6, 0x01,
	0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a,
	0x08, 0x46, 0x69, 0x6c, 0x6c, 0x52, 0x6f, 0x6c, 0x6c, 0x12, 0x11, 0x2e, 0x72, 0x6f, 0x6c, 0x6c,
	0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x0d, 0x2e, 0x72,
	0x6f, 0x6c, 0x6c, 0x2e, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x3c, 0x0a,
	0x11, 0x48, 0x61, 0x73, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x6f,
	0x6c, 0x6c, 0x12, 0x12, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x11, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x48, 0x61,
	0x73, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x12, 0x14, 0x2e, 0x72, 0x6f, 0x6c,
	0x6c, 0x2e, 0x48, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x72, 0x6f, 0x6c, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x48, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67,
	0x3b, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roll_proto_rawDescOnce sync.Once
	file_roll_proto_rawDescData = file_roll_proto_rawDesc
)

func file_roll_proto_rawDescGZIP() []byte {
	file_roll_proto_rawDescOnce.Do(func() {
		file_roll_proto_rawDescData = protoimpl.X.CompressGZIP(file_roll_proto_rawDescData)
	})
	return file_roll_proto_rawDescData
}

var file_roll_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_roll_proto_goTypes = []interface{}{
	(*RollAnswer)(nil),     // 0: roll.RollAnswer
	(*RollAnswers)(nil),    // 1: roll.RollAnswers
	(*RollStatHist)(nil),   // 2: roll.RollStatHist
	(*RollUserData)(nil),   // 3: roll.RollUserData
	(*HasAnswered)(nil),    // 4: roll.HasAnswered
	(*Nothing)(nil),        // 5: roll.Nothing
	(*HisStatRequest)(nil), // 6: roll.HisStatRequest
}
var file_roll_proto_depIdxs = []int32{
	0, // 0: roll.RollAnswers.Answers:type_name -> roll.RollAnswer
	1, // 1: roll.RollService.FillRoll:input_type -> roll.RollAnswers
	3, // 2: roll.RollService.HasUserFilledRoll:input_type -> roll.RollUserData
	6, // 3: roll.RollService.GetHistStat:input_type -> roll.HisStatRequest
	5, // 4: roll.RollService.FillRoll:output_type -> roll.Nothing
	4, // 5: roll.RollService.HasUserFilledRoll:output_type -> roll.HasAnswered
	2, // 6: roll.RollService.GetHistStat:output_type -> roll.RollStatHist
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_roll_proto_init() }
func file_roll_proto_init() {
	if File_roll_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roll_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roll_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollAnswers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roll_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollStatHist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roll_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollUserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roll_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasAnswered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roll_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nothing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roll_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HisStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roll_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roll_proto_goTypes,
		DependencyIndexes: file_roll_proto_depIdxs,
		MessageInfos:      file_roll_proto_msgTypes,
	}.Build()
	File_roll_proto = out.File
	file_roll_proto_rawDesc = nil
	file_roll_proto_goTypes = nil
	file_roll_proto_depIdxs = nil
}
