global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['main_service:8079']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth_service:8086']

  - job_name: 'messenger'
    static_configs:
      - targets: ['messenger_service:8096']

  - job_name: 'realtime'
    static_configs:
      - targets: ['realtime_service:8091']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: 'pinspire'
    scheme: https
    static_configs:
    - targets: ['pinspire.online:8080']
