global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'auth'
    static_configs:
      - targets: ['host.docker.internal:8085']
